export const conferenceTeams = [
  {
    conference: "SEC",
    teams: [
      "Alabama",
      "Auburn",
      "Arkansas",
      "Florida",
      "Georgia",
      "Kentucky",
      "LSU",
      "Missouri",
      "Ole Miss",
      "Vanderbilt",
      "Texas A&M",
      "Mississippi State",
      "South Carolina",
      "Tennessee",
    ],
  },
  {
    conference: "ACC",
    teams: [
      "Florida State",
      "Georgia Tech",
      "Louisville",
      "Boston College",
      "NC State",
      "Duke",
      "North Carolina",
      "Wake Forest",
      "Syracuse",
      "Pittsburgh",
      "Clemson",
      "Virginia",
      "Virginia Tech",
      "Miami",
    ],
  },

  {
    conference: "PAC 12",
    teams: [
      "Arizona State",
      "Arizona",
      "Stanford",
      "California",
      "UCLA",
      "USC",
      "Colorado",
      "Oregon State",
      "Utah",
      "Washington",
      "Washington State",
      "Oregon",
    ],
  },

  {
    conference: "Big 10",
    teams: [
      "Northwestern",
      "Indiana",
      "Maryland",
      "Michigan State",
      "Michigan",
      "Minnesota",
      "Nebraska",
      "Rutgers",
      "Ohio State",
      "Penn State",
      "Wisconsin",
      "Illinois",
      "Iowa",
      "Purdue",
    ],
  },

  {
    conference: "Big 12",
    teams: [
      "Iowa State",
      "Oklahoma State",
      "Oklahoma",
      "Baylor",
      "Texas",
      "West Virginia",
      "Kansas",
      "Kansas State",
      "TCU",
      "Texas Tech",
    ],
  },
];
